name: Generate SBOM
on: [push]
jobs:
  Githug-Acions:
      runs-on: ubuntu-latest
      steps: 
      - run: curl -Lo $RUNNER_TEMP/licensight-scan -O https://licensight.s3.eu-central-1.amazonaws.com/latest/linux/licensight-scan
      - run: chmod +x $RUNNER_TEMP/licensight-scan
      - run: $RUNNER_TEMP/licensight-scan generate -a ${{ vars.LICENSIGHT_APPLICATION_NAME }} -d . -e ${{ vars.LICENSIGHT_URL }} -at ${{ vars.LICENSIGHT_ACCESS_TOKEN }}
